/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gbsperso2;

import com.mysql.jdbc.Connection;
import java.security.NoSuchAlgorithmException;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Idaex
 */
public class AjoutUtilisateur extends javax.swing.JDialog {

    private InterfaceGraphique fenetre;

    /**
     * Creates new form AjoutUtilisateur
     */
    public AjoutUtilisateur(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //positionnement au milieu de la fenetre parente
        this.setLocationRelativeTo(parent);
        //on stocke dans this.fenetre la référence vers la fenetre parente
        this.fenetre = (InterfaceGraphique) parent;
        jButtonCreerUtilisateur.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNom = new javax.swing.JTextField();
        jTextFieldPrenom = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldTelephone = new javax.swing.JTextField();
        jTextFieldAnneeEntree = new javax.swing.JTextField();
        jLabelNom1 = new javax.swing.JLabel();
        jLabelPrenom1 = new javax.swing.JLabel();
        jLabelEmail1 = new javax.swing.JLabel();
        jLabelTelephone1 = new javax.swing.JLabel();
        jLabelAnneeEntree1 = new javax.swing.JLabel();
        jLabelIdentifiant1 = new javax.swing.JLabel();
        jTextFieldIdentifiant = new javax.swing.JTextField();
        jLabelAdresse1 = new javax.swing.JLabel();
        jTextFieldAdresse = new javax.swing.JTextField();
        jLabelRole1 = new javax.swing.JLabel();
        jComboBoxRole = new javax.swing.JComboBox<>();
        jLabelPosition1 = new javax.swing.JLabel();
        jComboBoxPosition = new javax.swing.JComboBox<>();
        jButtonReinitialiser = new javax.swing.JButton();
        jButtonCreerUtilisateur = new javax.swing.JButton();
        jLabelMdp1 = new javax.swing.JLabel();
        jTextFieldMdp = new javax.swing.JTextField();
        jLabelSalaire1 = new javax.swing.JLabel();
        jButtonCalculeSalaire = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelNom1.setText("Nom :");

        jLabelPrenom1.setText("Prenom :");

        jLabelEmail1.setText("Courriel :");

        jLabelTelephone1.setText("Téléphone :");

        jLabelAnneeEntree1.setText("Année d'entrée :");

        jLabelIdentifiant1.setText("Identifiant :");

        jLabelAdresse1.setText("Adresse :");

        jLabelRole1.setText("Role :");

        jComboBoxRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Directeur", "Responsable", "Employe" }));

        jLabelPosition1.setText("Position :");

        jComboBoxPosition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dirigeant\t", "Cadre", "Non-cadre" }));

        jButtonReinitialiser.setText("Réinitialiser les champs");
        jButtonReinitialiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReinitialiserActionPerformed(evt);
            }
        });

        jButtonCreerUtilisateur.setText("Créer l'utilisateur");
        jButtonCreerUtilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreerUtilisateurActionPerformed(evt);
            }
        });

        jLabelMdp1.setText("Mot de passe :");

        jLabelSalaire1.setText("Salaire : ? euros");

        jButtonCalculeSalaire.setText("Calculer le salaire");
        jButtonCalculeSalaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalculeSalaireActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelSalaire1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelAnneeEntree1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldAnneeEntree))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelPrenom1)
                                    .addGap(48, 48, 48)
                                    .addComponent(jTextFieldPrenom))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelNom1)
                                    .addGap(66, 66, 66)
                                    .addComponent(jTextFieldNom))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelEmail1)
                                        .addComponent(jLabelTelephone1))
                                    .addGap(32, 32, 32)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jButtonReinitialiser, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(84, 84, 84)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelRole1)
                            .addComponent(jLabelAdresse1)
                            .addComponent(jLabelIdentifiant1)
                            .addComponent(jLabelPosition1)
                            .addComponent(jLabelMdp1))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldAdresse)
                            .addComponent(jTextFieldIdentifiant)
                            .addComponent(jComboBoxRole, 0, 140, Short.MAX_VALUE)
                            .addComponent(jComboBoxPosition, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldMdp)))
                    .addComponent(jButtonCalculeSalaire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCreerUtilisateur, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNom1)
                    .addComponent(jLabelIdentifiant1)
                    .addComponent(jTextFieldIdentifiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPrenom1)
                    .addComponent(jLabelMdp1)
                    .addComponent(jTextFieldMdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEmail1)
                    .addComponent(jLabelAdresse1)
                    .addComponent(jTextFieldAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelephone1)
                    .addComponent(jTextFieldTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRole1)
                    .addComponent(jComboBoxRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAnneeEntree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAnneeEntree1)
                    .addComponent(jLabelPosition1)
                    .addComponent(jComboBoxPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSalaire1)
                    .addComponent(jButtonCalculeSalaire))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonReinitialiser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCreerUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonReinitialiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReinitialiserActionPerformed
        jTextFieldAdresse.setText("");
        jTextFieldNom.setText("");
        jTextFieldPrenom.setText("");
        jTextFieldEmail.setText("");
        jTextFieldTelephone.setText("");
        jTextFieldAnneeEntree.setText("");
        jTextFieldIdentifiant.setText("");
        jTextFieldMdp.setText("");
        jLabelSalaire1.setText("Salaire : ? euros");
        jButtonCreerUtilisateur.setVisible(false);
    }//GEN-LAST:event_jButtonReinitialiserActionPerformed

    private void jButtonCreerUtilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreerUtilisateurActionPerformed
        try {
            //interrogation de la BD pour savoir si l'identifiant/mot de passe est correct
            //instanciation de la classe Driver du paquetage jdbc de mysql
            Class.forName("com.mysql.jdbc.Driver");
            //Chaine de connexion (prise dans l'onglet services)
            String connexionUrl = "jdbc:mysql://localhost/gsbperso?user=admin&password=wxcvbn";

            //etablissement de la connexion
            Connection maConnexion = (Connection) DriverManager.getConnection(connexionUrl);

            //requete
            Statement requete = maConnexion.createStatement();
            String identifiant = this.fenetre.leUtilisateur.getIdentif();
            String mdp = this.fenetre.leUtilisateur.getMdp();
            Integer leSalaire = 0;
            if (jComboBoxPosition.getSelectedIndex() + 1 == 1) {
                leSalaire = 5000;
            } else {
                if (jComboBoxPosition.getSelectedIndex() + 1 == 2) {
                    leSalaire = 3500;
                } else {
                    leSalaire = 2500;
                }
            }
            Integer anciennete = 2017-Integer.parseInt(jTextFieldAnneeEntree.getText());
            for (int i=1 ; i<=anciennete ; i++){
                leSalaire= leSalaire + (leSalaire * 3 / 100 );
            }
            JOptionPane.showMessageDialog(rootPane, "Salaire :"+leSalaire);
            
            jButtonCreerUtilisateur.setVisible(true);
            jLabelSalaire1.setText("Salaire : "+leSalaire.toString()+" euros");
            requete.executeUpdate("insert into utilisateurs (nom, prenom, adresse_ville, telephone, email, annee_entree, identifiant, mot_de_passe, idrole, salaire, idposition)  "
                    + "values ('" + jTextFieldNom.getText() + "','" + jTextFieldPrenom.getText() + "', '" + jTextFieldAdresse.getText() + "', '" + jTextFieldTelephone.getText() + "', "
                    + "'" + jTextFieldEmail.getText() + "', '" + jTextFieldAnneeEntree.getText() + "', '" + jTextFieldIdentifiant.getText() + "', '" + Outils.md5(jTextFieldMdp.getText()) + "',"
                    + " '" + (jComboBoxRole.getSelectedIndex() + 1) + "', '" + leSalaire + "', '" + (jComboBoxPosition.getSelectedIndex()+1) + "')");
            JOptionPane.showMessageDialog(rootPane, "Utilisateur crée");
            jButtonReinitialiser.doClick();
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, "Classe de connexion mysql non trouvee..." + ex.toString());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "SQL exception ... " + ex.toString());
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(Connexion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButtonCreerUtilisateurActionPerformed

    private void jButtonCalculeSalaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalculeSalaireActionPerformed
        Integer leSalaire = 0;
            if (jComboBoxPosition.getSelectedIndex() + 1 == 1) {
                leSalaire = 5000;
            } else {
                if (jComboBoxPosition.getSelectedIndex() + 1 == 2) {
                    leSalaire = 3500;
                } else {
                    leSalaire = 3500;
                }
            }
            Integer anciennete = 2017-Integer.parseInt(jTextFieldAnneeEntree.getText());
            for (int i=1 ; i<=anciennete ; i++){
                leSalaire= leSalaire + (leSalaire * 3 / 100 );
            }
            JOptionPane.showMessageDialog(rootPane, "Salaire :"+leSalaire);
            
            jButtonCreerUtilisateur.setVisible(true);
            jLabelSalaire1.setText("Salaire : "+leSalaire.toString()+" euros");
    }//GEN-LAST:event_jButtonCalculeSalaireActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjoutUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjoutUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjoutUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjoutUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AjoutUtilisateur dialog = new AjoutUtilisateur(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalculeSalaire;
    private javax.swing.JButton jButtonCreerUtilisateur;
    private javax.swing.JButton jButtonReinitialiser;
    private javax.swing.JComboBox<String> jComboBoxPosition;
    private javax.swing.JComboBox<String> jComboBoxRole;
    private javax.swing.JLabel jLabelAdresse1;
    private javax.swing.JLabel jLabelAnneeEntree1;
    private javax.swing.JLabel jLabelEmail1;
    private javax.swing.JLabel jLabelIdentifiant1;
    private javax.swing.JLabel jLabelMdp1;
    private javax.swing.JLabel jLabelNom1;
    private javax.swing.JLabel jLabelPosition1;
    private javax.swing.JLabel jLabelPrenom1;
    private javax.swing.JLabel jLabelRole1;
    private javax.swing.JLabel jLabelSalaire1;
    private javax.swing.JLabel jLabelTelephone1;
    private javax.swing.JTextField jTextFieldAdresse;
    private javax.swing.JTextField jTextFieldAnneeEntree;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldIdentifiant;
    private javax.swing.JTextField jTextFieldMdp;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldPrenom;
    private javax.swing.JTextField jTextFieldTelephone;
    // End of variables declaration//GEN-END:variables
}
