/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gbsperso2;

import com.mysql.jdbc.Connection;
import java.security.NoSuchAlgorithmException;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * Classe permettant d'ajouter un utilisateur à la base de donnée
 * @author Idaex
 */
public class AjoutUtilisateur extends javax.swing.JDialog {

    private InterfaceGraphique fenetre;

    /**
     * Creates new form AjoutUtilisateur
     */
    public AjoutUtilisateur(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //positionnement au milieu de la fenetre parente
        this.setLocationRelativeTo(parent);
        //on stocke dans this.fenetre la référence vers la fenetre parente
        this.fenetre = (InterfaceGraphique) parent;
        jButtonCreerUtilisateur.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNom = new javax.swing.JTextField();
        jTextFieldPrenom = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldTelephone = new javax.swing.JTextField();
        jTextFieldAnneeEntree = new javax.swing.JTextField();
        jLabelNom1 = new javax.swing.JLabel();
        jLabelPrenom1 = new javax.swing.JLabel();
        jLabelEmail1 = new javax.swing.JLabel();
        jLabelTelephone1 = new javax.swing.JLabel();
        jLabelAnneeEntree1 = new javax.swing.JLabel();
        jLabelIdentifiant1 = new javax.swing.JLabel();
        jTextFieldIdentifiant = new javax.swing.JTextField();
        jLabelAdresse1 = new javax.swing.JLabel();
        jTextFieldAdresse = new javax.swing.JTextField();
        jLabelRole1 = new javax.swing.JLabel();
        jComboBoxRole = new javax.swing.JComboBox<>();
        jLabelPosition1 = new javax.swing.JLabel();
        jComboBoxPosition = new javax.swing.JComboBox<>();
        jButtonReinitialiser = new javax.swing.JButton();
        jButtonCreerUtilisateur = new javax.swing.JButton();
        jLabelMdp1 = new javax.swing.JLabel();
        jLabelSalaire1 = new javax.swing.JLabel();
        jButtonCalculeSalaire = new javax.swing.JButton();
        jLabelEtatNom = new javax.swing.JLabel();
        jLabelEtatPrenom = new javax.swing.JLabel();
        jLabelEtatEmail = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelEtatTelephone = new javax.swing.JLabel();
        jLabelEtatAnneeEntree = new javax.swing.JLabel();
        jLabelEtatIdentifiant = new javax.swing.JLabel();
        jLabelEtatMdp = new javax.swing.JLabel();
        jLabelEtatMdpCopie = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordFieldCopie = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextFieldNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldNomKeyReleased(evt);
            }
        });

        jTextFieldPrenom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPrenomKeyReleased(evt);
            }
        });

        jTextFieldEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldEmailKeyReleased(evt);
            }
        });

        jTextFieldTelephone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldTelephoneKeyReleased(evt);
            }
        });

        jTextFieldAnneeEntree.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldAnneeEntreeKeyReleased(evt);
            }
        });

        jLabelNom1.setText("Nom :");

        jLabelPrenom1.setText("Prenom :");

        jLabelEmail1.setText("Courriel :");

        jLabelTelephone1.setText("Téléphone :");

        jLabelAnneeEntree1.setText("Année d'entrée :");

        jLabelIdentifiant1.setText("Identifiant :");

        jTextFieldIdentifiant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldIdentifiantKeyReleased(evt);
            }
        });

        jLabelAdresse1.setText("Adresse :");

        jLabelRole1.setText("Role :");

        jComboBoxRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Directeur", "Responsable", "Employe" }));

        jLabelPosition1.setText("Position :");

        jComboBoxPosition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dirigeant\t", "Cadre", "Non-cadre" }));

        jButtonReinitialiser.setText("Réinitialiser les champs");
        jButtonReinitialiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReinitialiserActionPerformed(evt);
            }
        });

        jButtonCreerUtilisateur.setText("Créer l'utilisateur");
        jButtonCreerUtilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreerUtilisateurActionPerformed(evt);
            }
        });

        jLabelMdp1.setText("Mot de passe :");

        jLabelSalaire1.setText("Salaire : ? euros");

        jButtonCalculeSalaire.setText("Calculer le salaire");
        jButtonCalculeSalaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalculeSalaireActionPerformed(evt);
            }
        });

        jLabelEtatEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelEtatTelephone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelEtatAnneeEntree.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelEtatIdentifiant.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelEtatMdp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabelEtatMdpKeyReleased(evt);
            }
        });

        jLabelEtatMdpCopie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabelEtatMdpCopieKeyReleased(evt);
            }
        });

        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyReleased(evt);
            }
        });

        jPasswordFieldCopie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldCopieActionPerformed(evt);
            }
        });
        jPasswordFieldCopie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordFieldCopieKeyReleased(evt);
            }
        });

        jLabel1.setText("Retaper :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelEtatTelephone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(551, 551, 551))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelPrenom1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(jLabelEtatPrenom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                                        .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(103, 103, 103)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelTelephone1)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(74, 74, 74))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNom1)
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelEtatNom, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonCalculeSalaire, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonCreerUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelEtatMdp, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabelAnneeEntree1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldAnneeEntree, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabelEtatAnneeEntree, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(251, 251, 251)
                            .addComponent(jComboBoxPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabelEmail1)
                                    .addGap(338, 338, 338)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelRole1)
                                        .addComponent(jLabelAdresse1)
                                        .addComponent(jLabelPosition1))
                                    .addGap(48, 48, 48))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabelIdentifiant1)
                                    .addGap(42, 42, 42))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabelMdp1)
                                    .addGap(25, 25, 25)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldIdentifiant)
                                .addComponent(jTextFieldAdresse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelEtatIdentifiant, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBoxRole, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEtatMdpCopie, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(52, 52, 52)
                                .addComponent(jPasswordFieldCopie, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelSalaire1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonReinitialiser, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabelEtatEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNom1)
                    .addComponent(jLabelIdentifiant1)
                    .addComponent(jTextFieldIdentifiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelEtatNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelEtatIdentifiant, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPrenom1)
                    .addComponent(jLabelMdp1)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelEtatPrenom, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(jLabelEtatMdp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordFieldCopie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelEtatMdpCopie, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAdresse1)
                    .addComponent(jTextFieldAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEmail1)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jLabelEtatEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelRole1)
                        .addGap(59, 59, 59))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBoxRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelTelephone1))
                                .addGap(1, 1, 1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(jLabelEtatTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)))
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAnneeEntree1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAnneeEntree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPosition1))
                .addGap(35, 35, 35)
                .addComponent(jLabelEtatAnneeEntree, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSalaire1)
                    .addComponent(jButtonCalculeSalaire))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonReinitialiser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCreerUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonReinitialiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReinitialiserActionPerformed
        jTextFieldAdresse.setText("");
        jTextFieldNom.setText("");
        jTextFieldPrenom.setText("");
        jTextFieldEmail.setText("");
        jTextFieldTelephone.setText("");
        jTextFieldAnneeEntree.setText("");
        jTextFieldIdentifiant.setText("");
        jPasswordField1.setText("");
        jLabelSalaire1.setText("Salaire : ? euros");
        jButtonCreerUtilisateur.setVisible(false);

    }//GEN-LAST:event_jButtonReinitialiserActionPerformed

    private void jButtonCreerUtilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreerUtilisateurActionPerformed
        if (jLabelEtatNom.getText() == "Nom non valide") {
            JOptionPane.showMessageDialog(rootPane, "Un ou plusieurs champs incorrect, veuillez recommencer");
        } else {
            if (jLabelEtatPrenom.getText() == "Prenom non valide") {
                JOptionPane.showMessageDialog(rootPane, "Un ou plusieurs champs incorrect, veuillez recommencer");
            } else {
                if (jLabelEtatEmail.getText() == "Email non valide") {
                    JOptionPane.showMessageDialog(rootPane, "Un ou plusieurs champs incorrect, veuillez recommencer");
                } else {
                    if (jLabelEtatTelephone.getText() == "Téléphone non valide") {
                    } else {
                        if (jLabelEtatIdentifiant.getText() == "Identifiant non valide") {
                            JOptionPane.showMessageDialog(rootPane, "Un ou plusieurs champs incorrect, veuillez recommencer");
                        } else {
                            if (jLabelEtatMdp.getText() == "Mot de passe non valide") {
                                JOptionPane.showMessageDialog(rootPane, "Un ou plusieurs champs incorrect, veuillez recommencer");
                            } else {
                                if (jLabelEtatMdpCopie.getText() == "Les mots de passe ne correspondent pas") {

                                    JOptionPane.showMessageDialog(rootPane, "Les deux mots de passe ne correspondent pas !");
                                } else {
                                    try {
                                        //interrogation de la BD pour savoir si l'identifiant/mot de passe est correct
                                        //instanciation de la classe Driver du paquetage jdbc de mysql
                                        Class.forName("com.mysql.jdbc.Driver");
                                        //Chaine de connexion (prise dans l'onglet services)
                                        String connexionUrl = "jdbc:mysql://localhost/gsbperso?user=admin&password=wxcvbn";

                                        //etablissement de la connexion
                                        Connection maConnexion = (Connection) DriverManager.getConnection(connexionUrl);

                                        //requete
                                        Statement requete = maConnexion.createStatement();
                                        String identifiant = this.fenetre.leUtilisateur.getIdentif();
                                        String mdp = this.fenetre.leUtilisateur.getMdp();
                                        Integer leSalaire = 0;
                                        if (jComboBoxPosition.getSelectedIndex() + 1 == 1) {
                                            leSalaire = 5000;
                                        } else {
                                            if (jComboBoxPosition.getSelectedIndex() + 1 == 2) {
                                                leSalaire = 3500;
                                            } else {
                                                leSalaire = 2500;
                                            }
                                        }
                                        Integer anciennete = 2017 - Integer.parseInt(jTextFieldAnneeEntree.getText());
                                        for (int i = 1; i <= anciennete; i++) {
                                            leSalaire = leSalaire + (leSalaire * 3 / 100);
                                        }
                                        jButtonCreerUtilisateur.setVisible(true);
                                        jLabelSalaire1.setText("Salaire : " + leSalaire.toString() + " euros");
                                        requete.executeUpdate("insert into utilisateurs (nom, prenom, adresse_ville, telephone, email, annee_entree, identifiant, mot_de_passe, idrole, salaire, idposition)  "
                                                + "values ('" + jTextFieldNom.getText() + "','" + jTextFieldPrenom.getText() + "', '" + jTextFieldAdresse.getText() + "', '" + jTextFieldTelephone.getText() + "', "
                                                + "'" + jTextFieldEmail.getText() + "', '" + jTextFieldAnneeEntree.getText() + "', '" + jTextFieldIdentifiant.getText() + "', '" + Outils.md5(jPasswordField1.getText()) + "',"
                                                + " '" + (jComboBoxRole.getSelectedIndex() + 1) + "', '" + leSalaire + "', '" + (jComboBoxPosition.getSelectedIndex() + 1) + "')");
                                        JOptionPane.showMessageDialog(rootPane, "Utilisateur crée");
                                        jButtonReinitialiser.doClick();
                                    } catch (ClassNotFoundException ex) {
                                        JOptionPane.showMessageDialog(rootPane, "Classe de connexion mysql non trouvee..." + ex.toString());
                                    } catch (SQLException ex) {
                                        JOptionPane.showMessageDialog(rootPane, "SQL exception ... " + ex.toString());
                                    } catch (NoSuchAlgorithmException ex) {
                                        Logger.getLogger(Connexion.class.getName()).log(Level.SEVERE, null, ex);
                                    }
                                }
                            }
                        }
                    }

                }
            }
        }


    }//GEN-LAST:event_jButtonCreerUtilisateurActionPerformed

    private void jButtonCalculeSalaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalculeSalaireActionPerformed
        Integer leSalaire = 0;
        if (jComboBoxPosition.getSelectedIndex() + 1 == 1) {
            leSalaire = 5000;
        } else {
            if (jComboBoxPosition.getSelectedIndex() + 1 == 2) {
                leSalaire = 3500;
            } else {
                leSalaire = 3500;
            }
        }
        Integer anciennete = 2017 - Integer.parseInt(jTextFieldAnneeEntree.getText());
        for (int i = 1; i <= anciennete; i++) {
            leSalaire = leSalaire + (leSalaire * 3 / 100);
        }
        
        jButtonCreerUtilisateur.setVisible(true);
        jLabelSalaire1.setText("Salaire : " + leSalaire.toString() + " euros");
    }//GEN-LAST:event_jButtonCalculeSalaireActionPerformed

    private void jTextFieldNomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomKeyReleased
        boolean status = this.fenetre.leUtilisateur.validateNom(jTextFieldNom.getText());
        if (status) {
            jLabelEtatNom.setText("Nom valide");
        } else {
            jLabelEtatNom.setText("Nom non valide");
        }
    }//GEN-LAST:event_jTextFieldNomKeyReleased

    private void jTextFieldPrenomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrenomKeyReleased
        boolean status = this.fenetre.leUtilisateur.validatePrenom(jTextFieldPrenom.getText());
        if (status) {
            jLabelEtatPrenom.setText("Prenom valide");
        } else {
            jLabelEtatPrenom.setText("Prenom non valide");
        }
    }//GEN-LAST:event_jTextFieldPrenomKeyReleased

    private void jTextFieldEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEmailKeyReleased
        boolean status = this.fenetre.leUtilisateur.validateEmail(jTextFieldEmail.getText());
        if (status) {
            jLabelEtatEmail.setText("Email valide");
        } else {
            jLabelEtatEmail.setText("Email non valide");
        }
    }//GEN-LAST:event_jTextFieldEmailKeyReleased

    private void jTextFieldTelephoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTelephoneKeyReleased
        boolean status = this.fenetre.leUtilisateur.validateTelephone(jTextFieldTelephone.getText());
        if (status) {
            jLabelEtatTelephone.setText("Téléphone valide");
        } else {
            jLabelEtatTelephone.setText("Téléphone non valide");
        }
    }//GEN-LAST:event_jTextFieldTelephoneKeyReleased

    private void jTextFieldAnneeEntreeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAnneeEntreeKeyReleased
        boolean status = this.fenetre.leUtilisateur.validateAnneeEntree(jTextFieldAnneeEntree.getText());
        if (status) {
            jLabelEtatAnneeEntree.setText("Année valide");
        } else {
            jLabelEtatAnneeEntree.setText("Année non valide");
        }
    }//GEN-LAST:event_jTextFieldAnneeEntreeKeyReleased

    private void jTextFieldIdentifiantKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIdentifiantKeyReleased
        boolean status = this.fenetre.leUtilisateur.validateIdentifiant(jTextFieldIdentifiant.getText());
        if (status) {
            jLabelEtatIdentifiant.setText("Identifiant valide");
        } else {
            jLabelEtatIdentifiant.setText("Identifiant non valide");
        }
    }//GEN-LAST:event_jTextFieldIdentifiantKeyReleased

    private void jLabelEtatMdpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabelEtatMdpKeyReleased
        boolean status = this.fenetre.leUtilisateur.validateMdp(jPasswordField1.getText());
        if (status) {
            jLabelEtatMdp.setText("Mot de passe valide");
        } else {
            jLabelEtatMdp.setText("Mot de passe non valide");
        }
    }//GEN-LAST:event_jLabelEtatMdpKeyReleased

    private void jLabelEtatMdpCopieKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabelEtatMdpCopieKeyReleased

    }//GEN-LAST:event_jLabelEtatMdpCopieKeyReleased

    private void jPasswordFieldCopieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldCopieActionPerformed
        
    }//GEN-LAST:event_jPasswordFieldCopieActionPerformed

    private void jPasswordFieldCopieKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldCopieKeyReleased
        if(jPasswordField1.getText() == ""){
            jLabelEtatMdpCopie.setText("");
        }else{
            if(jPasswordField1.getText().equals(jPasswordFieldCopie.getText())){
                jLabelEtatMdpCopie.setText("Les mots de passe sont identiques");
            }else{
                jLabelEtatMdpCopie.setText("Les mots de passe ne correspondent pas");
            }
        }
    }//GEN-LAST:event_jPasswordFieldCopieKeyReleased

    private void jPasswordField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyReleased
        if(jPasswordField1.getText().equals(jPasswordFieldCopie.getText())){
            jLabelEtatMdpCopie.setText("Les mots de passe sont identiques");
        }else{
            jLabelEtatMdpCopie.setText("Les mots de passe ne correspondent pas");
        }
    }//GEN-LAST:event_jPasswordField1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjoutUtilisateur.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjoutUtilisateur.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjoutUtilisateur.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjoutUtilisateur.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AjoutUtilisateur dialog = new AjoutUtilisateur(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalculeSalaire;
    private javax.swing.JButton jButtonCreerUtilisateur;
    private javax.swing.JButton jButtonReinitialiser;
    private javax.swing.JComboBox<String> jComboBoxPosition;
    private javax.swing.JComboBox<String> jComboBoxRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelAdresse1;
    private javax.swing.JLabel jLabelAnneeEntree1;
    private javax.swing.JLabel jLabelEmail1;
    private javax.swing.JLabel jLabelEtatAnneeEntree;
    private javax.swing.JLabel jLabelEtatEmail;
    private javax.swing.JLabel jLabelEtatIdentifiant;
    private javax.swing.JLabel jLabelEtatMdp;
    private javax.swing.JLabel jLabelEtatMdpCopie;
    private javax.swing.JLabel jLabelEtatNom;
    private javax.swing.JLabel jLabelEtatPrenom;
    private javax.swing.JLabel jLabelEtatTelephone;
    private javax.swing.JLabel jLabelIdentifiant1;
    private javax.swing.JLabel jLabelMdp1;
    private javax.swing.JLabel jLabelNom1;
    private javax.swing.JLabel jLabelPosition1;
    private javax.swing.JLabel jLabelPrenom1;
    private javax.swing.JLabel jLabelRole1;
    private javax.swing.JLabel jLabelSalaire1;
    private javax.swing.JLabel jLabelTelephone1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordFieldCopie;
    private javax.swing.JTextField jTextFieldAdresse;
    private javax.swing.JTextField jTextFieldAnneeEntree;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldIdentifiant;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldPrenom;
    private javax.swing.JTextField jTextFieldTelephone;
    // End of variables declaration//GEN-END:variables
}
