/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gbsperso2;

import com.mysql.jdbc.Connection;
import java.security.NoSuchAlgorithmException;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Idaex
 */
public class AjoutUtilisateur extends javax.swing.JDialog {

    private InterfaceGraphique fenetre;

    /**
     * Creates new form AjoutUtilisateur
     */
    public AjoutUtilisateur(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //positionnement au milieu de la fenetre parente
        this.setLocationRelativeTo(parent);
        //on stocke dans this.fenetre la référence vers la fenetre parente
        this.fenetre = (InterfaceGraphique) parent;
        jButtonCreerUtilisateur.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNom = new javax.swing.JTextField();
        jTextFieldPrenom = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldTelephone = new javax.swing.JTextField();
        jTextFieldAnneeEntree = new javax.swing.JTextField();
        jLabelNom1 = new javax.swing.JLabel();
        jLabelPrenom1 = new javax.swing.JLabel();
        jLabelEmail1 = new javax.swing.JLabel();
        jLabelTelephone1 = new javax.swing.JLabel();
        jLabelAnneeEntree1 = new javax.swing.JLabel();
        jLabelIdentifiant1 = new javax.swing.JLabel();
        jTextFieldIdentifiant = new javax.swing.JTextField();
        jLabelAdresse1 = new javax.swing.JLabel();
        jTextFieldAdresse = new javax.swing.JTextField();
        jLabelRole1 = new javax.swing.JLabel();
        jComboBoxRole = new javax.swing.JComboBox<>();
        jLabelPosition1 = new javax.swing.JLabel();
        jComboBoxPosition = new javax.swing.JComboBox<>();
        jButtonReinitialiser = new javax.swing.JButton();
        jButtonCreerUtilisateur = new javax.swing.JButton();
        jLabelMdp1 = new javax.swing.JLabel();
        jTextFieldMdp = new javax.swing.JTextField();
        jLabelSalaire1 = new javax.swing.JLabel();
        jButtonCalculeSalaire = new javax.swing.JButton();
        jLabelEtatNom = new javax.swing.JLabel();
        jLabelEtatPrenom = new javax.swing.JLabel();
        jLabelEtatEmail = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelEtatEmail1 = new javax.swing.JLabel();
        jLabelEtatTelephone = new javax.swing.JLabel();
        jLabelEtatAnneeEntree = new javax.swing.JLabel();
        jLabelEtatIdentifiant = new javax.swing.JLabel();
        jLabelEtatMdp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextFieldNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldNomKeyReleased(evt);
            }
        });

        jTextFieldPrenom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPrenomKeyReleased(evt);
            }
        });

        jTextFieldEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldEmailKeyReleased(evt);
            }
        });

        jTextFieldTelephone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldTelephoneKeyReleased(evt);
            }
        });

        jTextFieldAnneeEntree.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldAnneeEntreeKeyReleased(evt);
            }
        });

        jLabelNom1.setText("Nom :");

        jLabelPrenom1.setText("Prenom :");

        jLabelEmail1.setText("Courriel :");

        jLabelTelephone1.setText("Téléphone :");

        jLabelAnneeEntree1.setText("Année d'entrée :");

        jLabelIdentifiant1.setText("Identifiant :");

        jTextFieldIdentifiant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldIdentifiantKeyReleased(evt);
            }
        });

        jLabelAdresse1.setText("Adresse :");

        jLabelRole1.setText("Role :");

        jComboBoxRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Directeur", "Responsable", "Employe" }));

        jLabelPosition1.setText("Position :");

        jComboBoxPosition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dirigeant\t", "Cadre", "Non-cadre" }));

        jButtonReinitialiser.setText("Réinitialiser les champs");
        jButtonReinitialiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReinitialiserActionPerformed(evt);
            }
        });

        jButtonCreerUtilisateur.setText("Créer l'utilisateur");
        jButtonCreerUtilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreerUtilisateurActionPerformed(evt);
            }
        });

        jLabelMdp1.setText("Mot de passe :");

        jLabelSalaire1.setText("Salaire : ? euros");

        jButtonCalculeSalaire.setText("Calculer le salaire");
        jButtonCalculeSalaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalculeSalaireActionPerformed(evt);
            }
        });

        jLabelEtatIdentifiant.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelEtatMdp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabelEtatMdpKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelNom1)
                                    .addGap(66, 66, 66)
                                    .addComponent(jTextFieldNom))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelPrenom1)
                                    .addGap(48, 48, 48)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelEtatPrenom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldPrenom)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelEmail1)
                                    .addGap(47, 47, 47)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabelEtatTelephone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldTelephone, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                        .addComponent(jLabelEtatEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelAnneeEntree1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelEtatAnneeEntree, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldAnneeEntree)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabelEtatEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE)))))
                            .addComponent(jButtonReinitialiser, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelEtatNom, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))
                            .addComponent(jLabelTelephone1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEtatIdentifiant, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEtatMdp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabelSalaire1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelIdentifiant1)
                                            .addComponent(jLabelMdp1))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelRole1)
                                            .addComponent(jLabelAdresse1)
                                            .addComponent(jLabelPosition1))
                                        .addGap(48, 48, 48)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldAdresse)
                                    .addComponent(jTextFieldIdentifiant)
                                    .addComponent(jComboBoxRole, 0, 140, Short.MAX_VALUE)
                                    .addComponent(jComboBoxPosition, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldMdp)))
                            .addComponent(jButtonCalculeSalaire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCreerUtilisateur, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNom1)
                    .addComponent(jLabelIdentifiant1)
                    .addComponent(jTextFieldIdentifiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelEtatNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelEtatIdentifiant, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPrenom1)
                    .addComponent(jLabelMdp1)
                    .addComponent(jTextFieldMdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelEtatPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabelEtatMdp, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEmail1)
                    .addComponent(jLabelAdresse1)
                    .addComponent(jTextFieldAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEtatEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelephone1)
                    .addComponent(jTextFieldTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRole1)
                    .addComponent(jComboBoxRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEtatTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPosition1)
                            .addComponent(jComboBoxPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAnneeEntree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelEtatEmail1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAnneeEntree1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelEtatAnneeEntree, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSalaire1)
                    .addComponent(jButtonCalculeSalaire))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonReinitialiser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCreerUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonReinitialiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReinitialiserActionPerformed
        jTextFieldAdresse.setText("");
        jTextFieldNom.setText("");
        jTextFieldPrenom.setText("");
        jTextFieldEmail.setText("");
        jTextFieldTelephone.setText("");
        jTextFieldAnneeEntree.setText("");
        jTextFieldIdentifiant.setText("");
        jTextFieldMdp.setText("");
        jLabelSalaire1.setText("Salaire : ? euros");
        jButtonCreerUtilisateur.setVisible(false);
    }//GEN-LAST:event_jButtonReinitialiserActionPerformed

    private void jButtonCreerUtilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreerUtilisateurActionPerformed
        if (jLabelEtatNom.getText() == "Nom non valide") {
            JOptionPane.showMessageDialog(rootPane, "Un ou plusieurs champs incorrect, veuillez recommencer");
        } else {
            if (jLabelEtatPrenom.getText() == "Prenom non valide") {
                JOptionPane.showMessageDialog(rootPane, "Un ou plusieurs champs incorrect, veuillez recommencer");
            } else {
                if (jLabelEtatEmail.getText() == "Email non valide") {
                    JOptionPane.showMessageDialog(rootPane, "Un ou plusieurs champs incorrect, veuillez recommencer");
                } else {
                    if (jLabelEtatTelephone.getText() == "Téléphone non valide") {
                    } else {
                        if (jLabelEtatIdentifiant.getText() == "Identifiant non valide") {
                            JOptionPane.showMessageDialog(rootPane, "Un ou plusieurs champs incorrect, veuillez recommencer");
                        }else{
                            if (jLabelEtatMdp.getText() == "Mot de passe non valide") {
                                JOptionPane.showMessageDialog(rootPane, "Un ou plusieurs champs incorrect, veuillez recommencer");
                            }
                        }
                        try {
                            //interrogation de la BD pour savoir si l'identifiant/mot de passe est correct
                            //instanciation de la classe Driver du paquetage jdbc de mysql
                            Class.forName("com.mysql.jdbc.Driver");
                            //Chaine de connexion (prise dans l'onglet services)
                            String connexionUrl = "jdbc:mysql://localhost/gsbperso?user=admin&password=wxcvbn";

                            //etablissement de la connexion
                            Connection maConnexion = (Connection) DriverManager.getConnection(connexionUrl);

                            //requete
                            Statement requete = maConnexion.createStatement();
                            String identifiant = this.fenetre.leUtilisateur.getIdentif();
                            String mdp = this.fenetre.leUtilisateur.getMdp();
                            Integer leSalaire = 0;
                            if (jComboBoxPosition.getSelectedIndex() + 1 == 1) {
                                leSalaire = 5000;
                            } else {
                                if (jComboBoxPosition.getSelectedIndex() + 1 == 2) {
                                    leSalaire = 3500;
                                } else {
                                    leSalaire = 2500;
                                }
                            }
                            Integer anciennete = 2017 - Integer.parseInt(jTextFieldAnneeEntree.getText());
                            for (int i = 1; i <= anciennete; i++) {
                                leSalaire = leSalaire + (leSalaire * 3 / 100);
                            }
                            jButtonCreerUtilisateur.setVisible(true);
                            jLabelSalaire1.setText("Salaire : " + leSalaire.toString() + " euros");
                            requete.executeUpdate("insert into utilisateurs (nom, prenom, adresse_ville, telephone, email, annee_entree, identifiant, mot_de_passe, idrole, salaire, idposition)  "
                                    + "values ('" + jTextFieldNom.getText() + "','" + jTextFieldPrenom.getText() + "', '" + jTextFieldAdresse.getText() + "', '" + jTextFieldTelephone.getText() + "', "
                                    + "'" + jTextFieldEmail.getText() + "', '" + jTextFieldAnneeEntree.getText() + "', '" + jTextFieldIdentifiant.getText() + "', '" + Outils.md5(jTextFieldMdp.getText()) + "',"
                                    + " '" + (jComboBoxRole.getSelectedIndex() + 1) + "', '" + leSalaire + "', '" + (jComboBoxPosition.getSelectedIndex() + 1) + "')");
                            JOptionPane.showMessageDialog(rootPane, "Utilisateur crée");
                            jButtonReinitialiser.doClick();
                        } catch (ClassNotFoundException ex) {
                            JOptionPane.showMessageDialog(rootPane, "Classe de connexion mysql non trouvee..." + ex.toString());
                        } catch (SQLException ex) {
                            JOptionPane.showMessageDialog(rootPane, "SQL exception ... " + ex.toString());
                        } catch (NoSuchAlgorithmException ex) {
                            Logger.getLogger(Connexion.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
            }
        }


    }//GEN-LAST:event_jButtonCreerUtilisateurActionPerformed

    private void jButtonCalculeSalaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalculeSalaireActionPerformed
        Integer leSalaire = 0;
        if (jComboBoxPosition.getSelectedIndex() + 1 == 1) {
            leSalaire = 5000;
        } else {
            if (jComboBoxPosition.getSelectedIndex() + 1 == 2) {
                leSalaire = 3500;
            } else {
                leSalaire = 3500;
            }
        }
        Integer anciennete = 2017 - Integer.parseInt(jTextFieldAnneeEntree.getText());
        for (int i = 1; i <= anciennete; i++) {
            leSalaire = leSalaire + (leSalaire * 3 / 100);
        }
        JOptionPane.showMessageDialog(rootPane, "Salaire :" + leSalaire);

        jButtonCreerUtilisateur.setVisible(true);
        jLabelSalaire1.setText("Salaire : " + leSalaire.toString() + " euros");
    }//GEN-LAST:event_jButtonCalculeSalaireActionPerformed

    private void jTextFieldNomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomKeyReleased
        boolean status = this.fenetre.leUtilisateur.validateNom(jTextFieldNom.getText());
        if (status) {
            jLabelEtatNom.setText("Nom valide");
        } else {
            jLabelEtatNom.setText("Nom non valide");
        }
    }//GEN-LAST:event_jTextFieldNomKeyReleased

    private void jTextFieldPrenomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrenomKeyReleased
        boolean status = this.fenetre.leUtilisateur.validatePrenom(jTextFieldPrenom.getText());
        if (status) {
            jLabelEtatPrenom.setText("Prenom valide");
        } else {
            jLabelEtatPrenom.setText("Prenom non valide");
        }
    }//GEN-LAST:event_jTextFieldPrenomKeyReleased

    private void jTextFieldEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEmailKeyReleased
        boolean status = this.fenetre.leUtilisateur.validateEmail(jTextFieldEmail.getText());
        if (status) {
            jLabelEtatEmail.setText("Email valide");
        } else {
            jLabelEtatEmail.setText("Email non valide");
        }
    }//GEN-LAST:event_jTextFieldEmailKeyReleased

    private void jTextFieldTelephoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTelephoneKeyReleased
        boolean status = this.fenetre.leUtilisateur.validateTelephone(jTextFieldTelephone.getText());
        if (status) {
            jLabelEtatTelephone.setText("Téléphone valide");
        } else {
            jLabelEtatTelephone.setText("Téléphone non valide");
        }
    }//GEN-LAST:event_jTextFieldTelephoneKeyReleased

    private void jTextFieldAnneeEntreeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAnneeEntreeKeyReleased
        boolean status = this.fenetre.leUtilisateur.validateAnneeEntree(jTextFieldAnneeEntree.getText());
        if (status) {
            jLabelEtatAnneeEntree.setText("Année valide");
        } else {
            jLabelEtatAnneeEntree.setText("Année non valide");
        }
    }//GEN-LAST:event_jTextFieldAnneeEntreeKeyReleased

    private void jTextFieldIdentifiantKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIdentifiantKeyReleased
        boolean status = this.fenetre.leUtilisateur.validateIdentifiant(jTextFieldIdentifiant.getText());
        if (status) {
            jLabelEtatIdentifiant.setText("Identifiant valide");
        } else {
            jLabelEtatIdentifiant.setText("Identifiant non valide");
        }
    }//GEN-LAST:event_jTextFieldIdentifiantKeyReleased

    private void jLabelEtatMdpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabelEtatMdpKeyReleased
        boolean status = this.fenetre.leUtilisateur.validateMdp(jTextFieldMdp.getText());
        if (status) {
            jLabelEtatMdp.setText("Mot de passe valide");
        } else {
            jLabelEtatMdp.setText("Mot de passe non valide");
        }
    }//GEN-LAST:event_jLabelEtatMdpKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjoutUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjoutUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjoutUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjoutUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AjoutUtilisateur dialog = new AjoutUtilisateur(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalculeSalaire;
    private javax.swing.JButton jButtonCreerUtilisateur;
    private javax.swing.JButton jButtonReinitialiser;
    private javax.swing.JComboBox<String> jComboBoxPosition;
    private javax.swing.JComboBox<String> jComboBoxRole;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelAdresse1;
    private javax.swing.JLabel jLabelAnneeEntree1;
    private javax.swing.JLabel jLabelEmail1;
    private javax.swing.JLabel jLabelEtatAnneeEntree;
    private javax.swing.JLabel jLabelEtatEmail;
    private javax.swing.JLabel jLabelEtatEmail1;
    private javax.swing.JLabel jLabelEtatIdentifiant;
    private javax.swing.JLabel jLabelEtatMdp;
    private javax.swing.JLabel jLabelEtatNom;
    private javax.swing.JLabel jLabelEtatPrenom;
    private javax.swing.JLabel jLabelEtatTelephone;
    private javax.swing.JLabel jLabelIdentifiant1;
    private javax.swing.JLabel jLabelMdp1;
    private javax.swing.JLabel jLabelNom1;
    private javax.swing.JLabel jLabelPosition1;
    private javax.swing.JLabel jLabelPrenom1;
    private javax.swing.JLabel jLabelRole1;
    private javax.swing.JLabel jLabelSalaire1;
    private javax.swing.JLabel jLabelTelephone1;
    private javax.swing.JTextField jTextFieldAdresse;
    private javax.swing.JTextField jTextFieldAnneeEntree;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldIdentifiant;
    private javax.swing.JTextField jTextFieldMdp;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldPrenom;
    private javax.swing.JTextField jTextFieldTelephone;
    // End of variables declaration//GEN-END:variables
}
