/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gbsperso2;

import com.mysql.jdbc.Connection;
import java.security.NoSuchAlgorithmException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * Classe permettant de modifier les informations d'un utilisateurs.
 * @author Idaex
 */
public class ModifInfos extends javax.swing.JDialog {

    private InterfaceGraphique fenetre;
    private Personne leUtilisateurModif;

    /**
     * Creates new form ModifInfos
     */
    public ModifInfos(java.awt.Frame parent, boolean modal, Personne unUtilisateur) {
        super(parent, modal);
        initComponents();
        //positionnement au milieu de la fenetre parente
        this.setLocationRelativeTo(parent);
        //on stocke dans this.fenetre la référence vers la fenetre parente
        this.fenetre = (InterfaceGraphique) parent;
        jTextFieldRole.setVisible(false);
        jTextFieldPosition.setVisible(false);
        jTextFieldAnneeEntree.setVisible(false);
        leUtilisateurModif = unUtilisateur;
        jTextFieldNom.setText(leUtilisateurModif.getNom());
        jTextFieldPrenom.setText(leUtilisateurModif.getPrenom());
        jTextFieldEmail.setText(leUtilisateurModif.getCourriel());
        jTextFieldTelephone.setText("0" + leUtilisateurModif.getTelephone().toString());
        jTextFieldAnneeEntree.setText(leUtilisateurModif.getAnneedentree().toString());
        jTextFieldIdentifiant.setText(leUtilisateurModif.getIdentif());
        jTextFieldAdresse.setText(leUtilisateurModif.getAdresse());
        jTextFieldRole.setText(leUtilisateurModif.getRoleentr());
        jTextFieldPosition.setText(leUtilisateurModif.getPosi());
        if (this.fenetre.leUtilisateur.getPosi() == "Responsable") {
            jTextFieldRole.setVisible(true);
            jTextFieldPosition.setVisible(true);
            jTextFieldAnneeEntree.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNom = new javax.swing.JTextField();
        jTextFieldPrenom = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldTelephone = new javax.swing.JTextField();
        jButtonValidModif = new javax.swing.JButton();
        jTextFieldAnneeEntree = new javax.swing.JTextField();
        jTextFieldIdentifiant = new javax.swing.JTextField();
        jTextFieldAdresse = new javax.swing.JTextField();
        jTextFieldRole = new javax.swing.JTextField();
        jTextFieldPosition = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButtonReinitialiser = new javax.swing.JButton();
        jLabelEtatEmail = new javax.swing.JLabel();
        jLabelEtatNom = new javax.swing.JLabel();
        jLabelEtatTelephone = new javax.swing.JLabel();
        jLabelEtatAnneeEntree = new javax.swing.JLabel();
        jLabelEtatPrenom = new javax.swing.JLabel();
        jLabelEtatIdentifiant = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextFieldNom.setText("Nom");
        jTextFieldNom.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextFieldNomInputMethodTextChanged(evt);
            }
        });
        jTextFieldNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNomKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldNomKeyReleased(evt);
            }
        });

        jTextFieldPrenom.setText("Prenom");
        jTextFieldPrenom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPrenomKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPrenomKeyReleased(evt);
            }
        });

        jTextFieldEmail.setText("Email");
        jTextFieldEmail.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextFieldEmailInputMethodTextChanged(evt);
            }
        });
        jTextFieldEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldEmailKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldEmailKeyReleased(evt);
            }
        });

        jTextFieldTelephone.setText("Téléphone");
        jTextFieldTelephone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldTelephoneKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldTelephoneKeyReleased(evt);
            }
        });

        jButtonValidModif.setText("Valider et modifier");
        jButtonValidModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidModifActionPerformed(evt);
            }
        });

        jTextFieldAnneeEntree.setText("Annee Entree");
        jTextFieldAnneeEntree.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldAnneeEntreeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldAnneeEntreeKeyReleased(evt);
            }
        });

        jTextFieldIdentifiant.setText("Identifiant");
        jTextFieldIdentifiant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldIdentifiantKeyReleased(evt);
            }
        });

        jTextFieldAdresse.setText("Adresse");
        jTextFieldAdresse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAdresseActionPerformed(evt);
            }
        });

        jTextFieldRole.setText("Role");

        jTextFieldPosition.setText("Position");

        jLabel1.setText("Nom :");

        jLabel2.setText("Prenom :");

        jLabel3.setText("Courriel :");

        jLabel4.setText("Téléphone :");

        jLabel5.setText("Année d'entrée :");

        jLabel6.setText("Identifiant :");

        jLabel7.setText("Adresse :");

        jLabel8.setText("Role :");

        jLabel9.setText("Position :");

        jButtonReinitialiser.setText("Réinitialiser les valeurs");
        jButtonReinitialiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReinitialiserActionPerformed(evt);
            }
        });

        jLabelEtatEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelEtatNom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelEtatTelephone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelEtatAnneeEntree.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel3)))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabelEtatNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTextFieldNom, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabelEtatPrenom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabelEtatEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8)))
                                .addGap(51, 51, 51))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldAnneeEntree, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(jLabelEtatTelephone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelEtatAnneeEntree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(374, 374, 374)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldAdresse)
                    .addComponent(jTextFieldIdentifiant)
                    .addComponent(jTextFieldRole)
                    .addComponent(jTextFieldPosition)
                    .addComponent(jButtonReinitialiser, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(jLabelEtatIdentifiant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(71, 71, 71))
            .addGroup(layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(jButtonValidModif, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIdentifiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelEtatNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelEtatIdentifiant, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jLabelEtatPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jLabelEtatEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelEtatTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAnneeEntree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jButtonReinitialiser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEtatAnneeEntree, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jButtonValidModif, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonValidModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidModifActionPerformed
        if (jLabelEtatNom.getText() == "Nom non valide") {
            JOptionPane.showMessageDialog(rootPane, "Un ou plusieurs champs incorrect, veuillez recommencer");
        } else {
            if (jLabelEtatPrenom.getText() == "Prenom non valide") {
                JOptionPane.showMessageDialog(rootPane, "Un ou plusieurs champs incorrect, veuillez recommencer");
            } else {
                if (jLabelEtatEmail.getText() == "Email non valide") {
                    JOptionPane.showMessageDialog(rootPane, "Un ou plusieurs champs incorrect, veuillez recommencer");
                } else {
                    if (jLabelEtatTelephone.getText() == "Téléphone non valide") {
                    } else {
                        if (jLabelEtatIdentifiant.getText() == "Identifiant non valide") {
                            JOptionPane.showMessageDialog(rootPane, "Un ou plusieurs champs incorrect, veuillez recommencer");
                        } else {

                            try {
                                //interrogation de la BD pour savoir si l'identifiant/mot de passe est correct
                                //instanciation de la classe Driver du paquetage jdbc de mysql
                                Class.forName("com.mysql.jdbc.Driver");
                                //Chaine de connexion (prise dans l'onglet services)
                                String connexionUrl = "jdbc:mysql://localhost/gsbperso?user=admin&password=wxcvbn";

                                //etablissement de la connexion
                                Connection maConnexion = (Connection) DriverManager.getConnection(connexionUrl);

                                //requete
                                Statement requete = maConnexion.createStatement();
                                String identifiant = this.fenetre.leUtilisateur.getIdentif();
                                String mdp = this.fenetre.leUtilisateur.getMdp();

                                //application du cryptage md5 au mdp
                                // ici on appelle md5 membre static de la classe outils
                                mdp = Outils.md5(mdp);
                                requete.executeUpdate("update utilisateurs set nom='" + jTextFieldNom.getText() + "', prenom='" + jTextFieldPrenom.getText() + "', email='" + jTextFieldEmail.getText() + "', telephone='" + jTextFieldTelephone.getText() + "' , adresse_ville='" + jTextFieldAdresse.getText() + "', identifiant='" + jTextFieldIdentifiant.getText() + "' , telephone='" + jTextFieldTelephone.getText() + "' where identifiant='" + identifiant + "' and mot_de_passe='" + mdp + "'");
                                // requete.executeUpdate("update utilisateurs set nom='"+jTextFieldNom.getText()+"', prenom='"+jTextFieldPrenom.getText()+"', email='"+jTextFieldEmail.getText()+"', telephone='"+jTextFieldTelephone.getText()+"',   where identifiant='" + identifiant + "' and mot_de_passe='" + mdp + "'");
                                //if (lignesRetour.next()) {
                                // String nom = lignesRetour.getString("nom");

                                //  } else {
                                JOptionPane.showMessageDialog(rootPane, "Modification effectué");
                                // };

                            } catch (ClassNotFoundException ex) {
                                JOptionPane.showMessageDialog(rootPane, "Classe de connexion mysql non trouvee..." + ex.toString());
                            } catch (SQLException ex) {
                                JOptionPane.showMessageDialog(rootPane, "SQL exception ... " + ex.toString());
                            } catch (NoSuchAlgorithmException ex) {
                                Logger.getLogger(Connexion.class.getName()).log(Level.SEVERE, null, ex);
                            }

                            this.fenetre.leUtilisateur.setNom(jTextFieldNom.getText());
                            this.fenetre.leUtilisateur.setPrenom(jTextFieldPrenom.getText());
                            this.fenetre.leUtilisateur.setCourriel(jTextFieldEmail.getText());
                            this.fenetre.leUtilisateur.setTelephone(Integer.parseInt(jTextFieldTelephone.getText()));
                            this.fenetre.leUtilisateur.setAnneedentree(Integer.parseInt(jTextFieldAnneeEntree.getText()));
                            this.fenetre.leUtilisateur.setAdresse(jTextFieldAdresse.getText());
                            this.fenetre.leUtilisateur.setIdentif(jTextFieldIdentifiant.getText());
                            this.fenetre.leUtilisateur.setRoleentr(jTextFieldRole.getText());
                            this.fenetre.leUtilisateur.setPosi(jTextFieldPosition.getText());
                            this.fenetre.majModifInfos();
                        }
                    }
                }
            }
        }


    }//GEN-LAST:event_jButtonValidModifActionPerformed

    private void jTextFieldAdresseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAdresseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAdresseActionPerformed

    private void jButtonReinitialiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReinitialiserActionPerformed
        jTextFieldNom.setText(leUtilisateurModif.getNom());
        jTextFieldPrenom.setText(leUtilisateurModif.getPrenom());
        jTextFieldEmail.setText(leUtilisateurModif.getCourriel());
        jTextFieldTelephone.setText("0" + leUtilisateurModif.getTelephone().toString());
        jTextFieldAnneeEntree.setText(leUtilisateurModif.getAnneedentree().toString());
        jTextFieldAdresse.setText(leUtilisateurModif.getAdresse());
        jTextFieldRole.setText(leUtilisateurModif.getRoleentr());
        jTextFieldPosition.setText(leUtilisateurModif.getPosi());
        jTextFieldIdentifiant.setText(leUtilisateurModif.getIdentif());
    }//GEN-LAST:event_jButtonReinitialiserActionPerformed

    private void jTextFieldEmailInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextFieldEmailInputMethodTextChanged

    }//GEN-LAST:event_jTextFieldEmailInputMethodTextChanged

    private void jTextFieldEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEmailKeyPressed

    }//GEN-LAST:event_jTextFieldEmailKeyPressed

    private void jTextFieldNomInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextFieldNomInputMethodTextChanged

    }//GEN-LAST:event_jTextFieldNomInputMethodTextChanged

    private void jTextFieldNomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomKeyPressed

    }//GEN-LAST:event_jTextFieldNomKeyPressed

    private void jTextFieldTelephoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTelephoneKeyPressed

    }//GEN-LAST:event_jTextFieldTelephoneKeyPressed

    private void jTextFieldPrenomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrenomKeyPressed

    }//GEN-LAST:event_jTextFieldPrenomKeyPressed

    private void jTextFieldAnneeEntreeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAnneeEntreeKeyPressed

    }//GEN-LAST:event_jTextFieldAnneeEntreeKeyPressed


    private void jTextFieldNomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomKeyReleased
        boolean status = leUtilisateurModif.validateNom(jTextFieldNom.getText());
        if (status) {
            jLabelEtatNom.setText("Nom valide");
        } else {
            jLabelEtatNom.setText("Nom non valide");
        }
    }//GEN-LAST:event_jTextFieldNomKeyReleased

    private void jTextFieldPrenomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrenomKeyReleased
        boolean status = leUtilisateurModif.validatePrenom(jTextFieldPrenom.getText());
        if (status) {
            jLabelEtatPrenom.setText("Prenom valide");
        } else {
            jLabelEtatPrenom.setText("Prenom non valide");
        }
    }//GEN-LAST:event_jTextFieldPrenomKeyReleased

    private void jTextFieldEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEmailKeyReleased
        boolean status = leUtilisateurModif.validateEmail(jTextFieldEmail.getText());
        if (status) {
            jLabelEtatEmail.setText("Email valide");
        } else {
            jLabelEtatEmail.setText("Email non valide");
        }
    }//GEN-LAST:event_jTextFieldEmailKeyReleased

    private void jTextFieldAnneeEntreeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAnneeEntreeKeyReleased
        boolean status = leUtilisateurModif.validateAnneeEntree(jTextFieldAnneeEntree.getText());
        if (status) {
            jLabelEtatAnneeEntree.setText("Année valide");
        } else {
            jLabelEtatAnneeEntree.setText("Année non valide");
        }
    }//GEN-LAST:event_jTextFieldAnneeEntreeKeyReleased

    private void jTextFieldTelephoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTelephoneKeyReleased
        boolean status = leUtilisateurModif.validateTelephone(jTextFieldTelephone.getText());
        if (status) {
            jLabelEtatTelephone.setText("Téléphone valide");
        } else {
            jLabelEtatTelephone.setText("Téléphone non valide");
        }
    }//GEN-LAST:event_jTextFieldTelephoneKeyReleased

    private void jTextFieldIdentifiantKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIdentifiantKeyReleased
        boolean status = this.fenetre.leUtilisateur.validateIdentifiant(jTextFieldIdentifiant.getText());
        if (status) {
            jLabelEtatIdentifiant.setText("Identifiant valide");
        } else {
            jLabelEtatIdentifiant.setText("Identifiant non valide");
        }
    }//GEN-LAST:event_jTextFieldIdentifiantKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifInfos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifInfos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifInfos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifInfos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModifInfos dialog = new ModifInfos(new javax.swing.JFrame(), true, new Personne());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonReinitialiser;
    private javax.swing.JButton jButtonValidModif;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelEtatAnneeEntree;
    private javax.swing.JLabel jLabelEtatEmail;
    private javax.swing.JLabel jLabelEtatIdentifiant;
    private javax.swing.JLabel jLabelEtatNom;
    private javax.swing.JLabel jLabelEtatPrenom;
    private javax.swing.JLabel jLabelEtatTelephone;
    private javax.swing.JTextField jTextFieldAdresse;
    private javax.swing.JTextField jTextFieldAnneeEntree;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldIdentifiant;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldPosition;
    private javax.swing.JTextField jTextFieldPrenom;
    private javax.swing.JTextField jTextFieldRole;
    private javax.swing.JTextField jTextFieldTelephone;
    // End of variables declaration//GEN-END:variables
}
